version: '3.9'

services:
  app:
    build: .
    ports:
      - 3000:3000
    restart: always
    networks:
      - mongonetwork

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "${ME_CONFIG_BASICAUTH_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${ME_CONFIG_BASICAUTH_PASSWORD}"
      ME_CONFIG_MONGODB_SERVER: "${MONGODB_SERVER}"
      ME_CONFIG_MONGODB_PORT: "${MONGODB_PORT}"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "${MONGODB_ENABLE_ADMIN}"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGODB_ADMINUSERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGODB_ADMINPASSWORD}"  
    links:
      - mongo
    networks:
      - mongonetwork

  mongo:
    image: mongo
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_ADMINUSERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_ADMINPASSWORD}"
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - mongonetwork

volumes:
  mongodb:

networks: 
  mongonetwork:
    driver: bridge